
const view=document.getElementById('view'),tabs=document.getElementById('tabs'),title=document.getElementById('title'),subtitle=document.getElementById('subtitle');let tg=null,initData='',me=null,section='dashboard',currentUser=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(s){const el=document.getElementById('toast');el.textContent=s;el.style.display='block';setTimeout(()=>el.style.display='none',2500)}
function headers(){return initData?{'Authorization':'tma '+initData}:{}
}
async function api(path,opt={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),10000);try{const res=await fetch(path,{...opt,signal:controller.signal,headers:{...headers(),...(opt.headers||{})}});if(!res.ok){let d={};try{d=await res.json()}catch{}throw new Error(d.error||('خطای HTTP '+res.status))}return await res.json()}catch(e){if(e.name==='AbortError')throw new Error('ارتباط با سرور بیش از حد طول کشید. اتصال اینترنت یا Worker را بررسی کنید.');throw e}finally{clearTimeout(timer)}}
function tab(id,label){return '<button class="'+(section===id?'active':'')+'" onclick="go(\''+id+'\')">'+label+'</button>'}
function renderTabs(){tabs.innerHTML=tab('dashboard','داشبورد')+tab('conversations','گفتگوها')+tab('canned','پاسخ‌های آماده')+((me?.admin?.role==='super_admin')?tab('admins','مدیران'):'')+tab('broadcast','اطلاع‌رسانی')+tab('stats','آمار')+tab('settings','تنظیمات')}
async function boot(){
  subtitle.textContent='در حال اتصال به Telegram… · نسخه ۶';
  tg=await loadTelegramBridge();
  try{tg.ready();tg.expand();}catch{}
  initData=String(tg.initData||'');
  if(!initData) throw new Error('اطلاعات احراز هویت Telegram دریافت نشد. پنل را ببندید و دوباره از داخل ربات باز کنید.');
  subtitle.textContent='در حال بررسی دسترسی…';
  const r=await api('/api/admin/me');
  me=r;subtitle.textContent='سلام '+esc(r.admin.display_name);renderTabs();await go('dashboard');
}
async function go(s){section=s;renderTabs();currentUser=null;try{if(s==='dashboard')return dashboard();if(s==='conversations')return conversations();if(s==='canned')return canned();if(s==='admins')return admins();if(s==='broadcast')return broadcast();if(s==='stats')return stats();if(s==='settings')return settings()}catch(e){view.innerHTML='<div class="card empty">'+esc(e.message)+'</div>'}}
async function dashboard(){const r=await api('/api/dashboard');view.innerHTML='<div class="grid"><div class="card stat"><b>'+r.stats.messages+'</b><span>پیام امروز</span></div><div class="card stat"><b>'+r.stats.open+'</b><span>گفتگوی باز</span></div><div class="card stat"><b>'+r.stats.unassigned+'</b><span>بدون مدیر</span></div><div class="card stat"><b>'+r.stats.activeAdmins+'</b><span>مدیر فعال</span></div></div><div class="card"><div class="section-title">دسترسی سریع</div><div class="toolbar"><button class="btn" onclick="go(&#39;conversations&#39;)">گفتگوها</button><button class="btn secondary" onclick="go(&#39;broadcast&#39;)">اطلاع‌رسانی</button></div></div>'}
async function conversations(page=1){const r=await api('/api/conversations?page='+page);view.innerHTML='<div class="card"><div class="toolbar"><input class="input" id="search" placeholder="جستجو نام، نام کاربری یا شناسه"><select id="assigned"><option value="">همه</option><option value="unassigned">بدون مدیر</option><option value="assigned">دارای مدیر</option></select><button class="btn" onclick="searchConversations()">جستجو</button></div></div><div id="convlist" class="list">'+(r.items.length?r.items.map(u=>'<button class="item" onclick="openConv('+u.id+')"><div class="row"><strong>'+esc([u.first_name,u.last_name].filter(Boolean).join(' ')||u.username||u.id)+'</strong><span class="pill '+(u.status==='blocked'?'red':'green')+'">'+(u.status==='blocked'?'مسدود':'فعال')+'</span></div><span class="preview">'+esc(u.unread_count?('🔔 '+u.unread_count+' خوانده‌نشده'):((u.tags||'')))+'</span></button>').join(''):'<div class="card empty">گفتگویی پیدا نشد.</div>')+'</div><div class="toolbar"><button class="btn secondary" onclick="conversations('+Math.max(1,page-1)+')">قبلی</button><button class="btn secondary" onclick="conversations(' + (page+1) + ')" '+(r.items.length<r.pageSize?'disabled':'')+'>بعدی</button></div>'}
async function searchConversations(){const q=encodeURIComponent(document.getElementById('search').value||'');const a=encodeURIComponent(document.getElementById('assigned').value||'');const r=await api('/api/conversations?q='+q+'&assigned='+a);document.getElementById('convlist').innerHTML=r.items.length?r.items.map(u=>'<button class="item" onclick="openConv('+u.id+')"><div class="row"><strong>'+esc([u.first_name,u.last_name].filter(Boolean).join(' ')||u.username||u.id)+'</strong><span class="pill">'+esc(u.admin_name||'بدون مدیر')+'</span></div><span class="preview">'+esc(u.username?'@'+u.username:'شناسه '+u.id)+'</span></button>').join(''):'<div class="card empty">نتیجه‌ای پیدا نشد.</div>'}
async function openConv(id){currentUser=id;const r=await api('/api/conversations/'+id);title.textContent='گفتگو';tabs.innerHTML='<button class="btn secondary" onclick="go(\'conversations\')">← بازگشت</button>';const name=[r.user.first_name,r.user.last_name].filter(Boolean).join(' ')||r.user.username||r.user.id;view.innerHTML='<div class="card"><div class="row"><div><strong>'+esc(name)+'</strong><div class="muted">'+esc(r.user.username?'@'+r.user.username:'شناسه '+r.user.id)+'</div></div><span class="pill '+(r.user.priority?'red':'')+'">'+(r.user.priority?'فوری':'عادی')+'</span></div><div class="toolbar" style="margin-top:8px"><button class="btn small" onclick="claim('+id+')">پاسخ دادن</button><button class="btn secondary small" onclick="release('+id+')">آزاد کردن</button><button class="btn danger small" onclick="'+(r.user.status==='blocked'?'unblockUser('+id+')':'blockUser('+id+')')+'">'+(r.user.status==='blocked'?'رفع مسدودی':'مسدود')+'</button><button class="btn secondary small" onclick="downloadExport('+id+')">خروجی CSV</button></div></div><div id="thread" class="thread">'+r.messages.map(m=>'<div class="msg '+(m.direction==='user_to_admin'?'user':'admin')+'"><div class="meta">'+esc(m.direction==='user_to_admin'?'کاربر':'مدیر')+' · '+esc(m.content_type)+'</div><div>'+esc(m.text_content||('['+m.content_type+']'))+'</div></div>').join('')+'</div><div class="card"><textarea id="reply" placeholder="پاسخ شما…"></textarea><div class="toolbar" style="margin-top:7px"><input id="media" type="file" accept="image/*,video/*,audio/*,.pdf,.doc,.docx,.zip" class="input"><button class="btn" onclick="sendReply('+id+')">ارسال پاسخ</button></div></div>'}
async function claim(id){await api('/api/conversations/'+id+'/claim',{method:'POST'});toast('گفتگو به شما واگذار شد.');openConv(id)} async function release(id){await api('/api/conversations/'+id+'/release',{method:'POST'});toast('گفتگو آزاد شد.');openConv(id)} async function blockUser(id){if(!confirm('این کاربر مسدود شود؟'))return;await api('/api/conversations/'+id+'/status',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({status:'blocked'})});toast('کاربر مسدود شد.');openConv(id)} async function unblockUser(id){if(!confirm('مسدودی این کاربر برداشته شود؟'))return;await api('/api/conversations/'+id+'/status',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({status:'active'})});toast('رفع مسدودی انجام شد.');openConv(id)}
async function downloadExport(id){const res=await fetch('/api/conversations/'+id+'/export',{headers:headers()});if(!res.ok){toast('دانلود ناموفق بود.');return}const blob=await res.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='conversation-'+id+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function sendReply(id){const fd=new FormData();fd.append('text',document.getElementById('reply').value||'');const f=document.getElementById('media').files[0];if(f)fd.append('media',f);try{await api('/api/conversations/'+id+'/reply',{method:'POST',body:fd});toast('✅ پاسخ ارسال شد.');openConv(id)}catch(e){toast(e.message)}}
async function canned(){const r=await api('/api/canned');view.innerHTML='<div class="card"><div class="section-title">پاسخ جدید</div><input id="cs" class="input" placeholder="میانبر"><input id="ct" class="input" style="margin-top:7px" placeholder="عنوان"><textarea id="cb" style="margin-top:7px" placeholder="متن پاسخ"></textarea><button class="btn" style="margin-top:7px" onclick="addCanned()">ثبت</button></div><div class="list">'+r.items.map(x=>'<div class="card"><div class="row"><strong>'+esc(x.title)+'</strong><button class="btn danger small" onclick="delCanned('+x.id+')">حذف</button></div><div class="muted">'+esc(x.shortcut)+'</div><div style="margin-top:5px">'+esc(x.body_text)+'</div></div>').join('')+'</div>'} async function addCanned(){await api('/api/canned',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({shortcut:document.getElementById('cs').value,title:document.getElementById('ct').value,body_text:document.getElementById('cb').value})});toast('ذخیره شد.');canned()} async function delCanned(id){await api('/api/canned/'+id,{method:'DELETE'});toast('حذف شد.');canned()}
async function admins(){if(me.admin.role!=='super_admin')return;const r=await api('/api/admins');view.innerHTML='<div class="card"><button class="btn" onclick="invite()">ساخت لینک دعوت</button><div id="invite"></div></div><div class="list">'+r.admins.map(a=>'<div class="card"><div class="row"><div><strong>'+esc(a.display_name)+'</strong><div class="muted">'+esc(a.role==='super_admin'?'مدیر ارشد':'مدیر')+' · '+a.id+'</div></div>'+((a.role==='admin')?'<button class="btn danger small" onclick="removeAdmin('+a.id+')">حذف</button>':'')+'</div></div>').join('')+'</div>'} async function invite(){const r=await api('/api/admins/invite',{method:'POST'});document.getElementById('invite').innerHTML='<div class="card"><div class="muted">لینک دعوت ۲۴ ساعته</div><input class="input" value="'+esc(r.url)+'" readonly><button class="btn secondary" style="margin-top:7px" onclick="navigator.clipboard?.writeText('+JSON.stringify(r.url)+');toast(\'کپی شد.\')">کپی لینک</button></div>'} async function removeAdmin(id){await api('/api/admins/'+id+'/remove',{method:'POST'});toast('مدیر غیرفعال شد.');admins()}
async function broadcast(){view.innerHTML='<div class="card"><div class="section-title">اطلاع‌رسانی همگانی</div><select id="seg" class="input"><option value="all">همه کاربران فعال</option><option value="30d">فعال در ۳۰ روز اخیر</option></select><textarea id="bt" style="margin-top:7px" placeholder="متن اطلاع‌رسانی"></textarea><input id="bm" type="file" class="input" style="margin-top:7px" accept="image/*,video/*,audio/*,.pdf,.doc,.docx,.zip"><button class="btn" style="margin-top:7px" onclick="startBroadcast()">شروع ارسال</button><div id="bprog" style="margin-top:10px"></div></div>'} async function startBroadcast(){const fd=new FormData();fd.append('segment',document.getElementById('seg').value);fd.append('text',document.getElementById('bt').value||'');const f=document.getElementById('bm').files[0];if(f)fd.append('media',f);const r=await api('/api/broadcast/start',{method:'POST',body:fd});let done=false;while(!done){const b=await api('/api/broadcast/batch',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({job_id:r.jobId})});document.getElementById('bprog').innerHTML='<div class="muted">ارسال: '+b.sent+' موفق، '+b.failed+' ناموفق از '+b.total+'</div><div class="bar"><i style="width:'+Math.min(100,Math.round((b.cursor/Math.max(1,b.total))*100))+'%"></i></div>';done=b.done;if(!done)await new Promise(x=>setTimeout(x,350))}toast('ارسال اطلاع‌رسانی تمام شد.')}
async function stats(){const r=await api('/api/stats');const max=Math.max(1,...r.volume.map(x=>Number(x.count)));view.innerHTML='<div class="card"><div class="section-title">حجم پیام در ۱۴ روز اخیر</div>'+r.volume.map(x=>'<div style="margin:8px 0"><div class="row"><span>'+esc(x.day)+'</span><span>'+x.count+'</span></div><div class="bar"><i style="width:'+Math.round(Number(x.count)/max*100)+'%"></i></div></div>').join('')+'</div><div class="card"><strong>'+Math.round(r.avgResponseSeconds/60)+'</strong><div class="muted">میانگین زمان پاسخ (دقیقه)</div></div>'}
async function settings(){const r=await api('/api/settings');const s=r.settings;view.innerHTML='<div class="card"><label><input type="checkbox" id="away" '+(s.away_mode==='1'?'checked':'')+'> حالت آفلاین</label><br><label><input type="checkbox" id="ack" '+(s.auto_ack==='1'?'checked':'')+'> تأیید خودکار دریافت پیام</label><br><label><input type="checkbox" id="bh" '+(s.business_hours_enabled==='1'?'checked':'')+'> ساعات کاری</label><input class="input" id="start" style="margin-top:10px" value="'+esc(s.business_hours_start||'09:00')+'" placeholder="شروع"><input class="input" id="end" style="margin-top:7px" value="'+esc(s.business_hours_end||'17:00')+'" placeholder="پایان"></div><div class="card"><div class="section-title">متن خوش‌آمدگویی</div><textarea id="welcome">'+esc(s.welcome_message||'')+'</textarea><div class="section-title">پیام دریافت شد</div><textarea id="ackmsg">'+esc(s.ack_message||'')+'</textarea><div class="section-title">پیام آفلاین</div><textarea id="awaymsg">'+esc(s.away_message||'')+'</textarea><button class="btn" style="margin-top:8px" onclick="saveSettings()">ذخیره تنظیمات</button></div>'} async function saveSettings(){const body={away_mode:document.getElementById('away').checked,auto_ack:document.getElementById('ack').checked,business_hours_enabled:document.getElementById('bh').checked,business_hours_start:document.getElementById('start').value,business_hours_end:document.getElementById('end').value,welcome_message:document.getElementById('welcome').value,ack_message:document.getElementById('ackmsg').value,away_message:document.getElementById('awaymsg').value};await api('/api/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(body)});toast('تنظیمات ذخیره شد.')}
async function loadTelegramBridge(){
  if(window.Telegram?.WebApp) return window.Telegram.WebApp;
  return await new Promise((resolve,reject)=>{
    const existing=document.querySelector('script[data-telegram-webapp]');
    if(existing){
      const started=Date.now();
      const poll=()=>{
        if(window.Telegram?.WebApp) return resolve(window.Telegram.WebApp);
        if(Date.now()-started>7000) return reject(new Error('کتابخانه رسمی Telegram در پنل بارگذاری نشد. پنل را ببندید و دوباره از داخل ربات باز کنید.'));
        setTimeout(poll,100);
      };
      poll();
      return;
    }
    const script=document.createElement('script');
    script.src='https://telegram.org/js/telegram-web-app.js?63';
    script.async=true;
    script.dataset.telegramWebapp='1';
    const timer=setTimeout(()=>{script.remove();reject(new Error('ارتباط با سرویس Telegram برای راه‌اندازی پنل برقرار نشد.'))},7000);
    script.onload=()=>{clearTimeout(timer); if(window.Telegram?.WebApp) resolve(window.Telegram.WebApp); else reject(new Error('Telegram WebApp API در دسترس نشد.'))};
    script.onerror=()=>{clearTimeout(timer);script.remove();reject(new Error('بارگذاری کتابخانه Telegram ناموفق بود. اتصال اینترنت را بررسی کنید.'))};
    document.head.appendChild(script);
  });
}

(async()=>{try{await boot()}catch(e){subtitle.textContent='خطا در راه‌اندازی پنل';view.innerHTML='<div class="card empty"><strong>پنل مدیریت آماده نشد.</strong><br><br>'+esc(e.message)+'</div>'}})();
